# Test IPYNB SetUp

- After your IPYNB setup is done, to check that Python is working properly, we should always check first by running the simplest "Hello World" program
  
- Make sure you have Jupyter Notebook setup locally working

- If you havno set-up for Jupyer Notebook, it is recommended to read [README.md](./README.md) 

- For showing the output of the cell of code or markdown, press `Shift + Enter` on the keyboard to view output

In [12]:
print("Hello, World!")

Hello, World!


Alright, since the output was printed as expected, now, we can move further.

## NumPy
### NumPy Introduction

**NumPy (Numerical Python)** is the foundational library for numerical and scientific computing in Python. It provides:

- An **efficient multi-dimensional array object**: `ndarray`
- Functions for **mathematical, logical, shape manipulation**, and more
- Tools for integrating C/C++ and Fortran code
- Capabilities for **Fourier transforms**, **linear algebra**, and **random number generation**

### Features of NumPy

- **Performance**: Arrays are stored in contiguous blocks of memory (like C), making operations lightning-fast.
- **Convenience**: Built-in broadcasting, vectorized operations, and slicing eliminate the need for loops.
- **Integration**: Widely used in `Pandas`, `Matplotlib`, `Scikit-learn`, `TensorFlow`, etc.

Let's get started with writing the code:

### Creating Arrays

In [13]:
# Importing only the required methods from NumPy 
from numpy import array, zeros, ones, eye, full, arange
from numpy.random import randint, rand

# 1D array
a = array([1, 2, 3, 4, 5, 6])
print(f"1-D array is:\n{a}\n")

# 2D array
b = array([[1, 2, 3], [4, 5, 6]])
print(f"2-D array is:\n{b}\n")

# Matrix of 0s
c = zeros((2, 3))
print(f"The matrix of 0s is:\n{c}\n")

# Matrix  of 1s
d = ones((3, 2))
print(f"The matrix of 1s is:\n{d}\n")

# Whole matrix of desired number
e = full((3, 3), 18)
print(f"Whole matrix of a desired number:\n{e}\n")

# Identity matrix
f = eye(3)
print(f"The identity matrix is:\n{f}\n")

# Matrix of random float numbers betweeen 0 and 1
g = rand(4, 3)
print(f"Matrix of random float numbers between 0 and 1 is:\n{g}\n")

# Matrix of random integers within specified range
h = randint(1, 11, (3, 4))
print(f"Matrix of random integers within specified range:\n{h}\n")

# Generating the array with specified range, in order
i = arange(1, 11, 1)
print(f"Array generated using arange() is:\n{i}\n")

1-D array is:
[1 2 3 4 5 6]

2-D array is:
[[1 2 3]
 [4 5 6]]

The matrix of 0s is:
[[0. 0. 0.]
 [0. 0. 0.]]

The matrix of 1s is:
[[1. 1.]
 [1. 1.]
 [1. 1.]]

Whole matrix of a desired number:
[[18 18 18]
 [18 18 18]
 [18 18 18]]

The identity matrix is:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Matrix of random float numbers between 0 and 1 is:
[[0.53039694 0.3815285  0.37326994]
 [0.80241925 0.47471995 0.2894575 ]
 [0.5955692  0.65404691 0.53990861]
 [0.6579835  0.49197371 0.96379414]]

Matrix of random integers within specified range:
[[ 4  4  6  3]
 [ 9 10  8  1]
 [ 1  2  8 10]]

Array generated using arange() is:
[ 1  2  3  4  5  6  7  8  9 10]



### Methods of arrays

In [14]:
from numpy import shape, ndim, size, dtype
from numpy.random import randint

a = randint(1, 11, (3, 3))
print(f"Generated array is:\n{a}\n")

# .shape gives the length x breadth size in a tuple
s = a.shape
print(f"Shape of the array is {s}\n")

# .ndim gives the dimension size of the array
d = a.ndim
print(f"The array is {d}-D\n")

# .size gives the number of total elements in the array
e = a.size
print(f"Total number of elements in the array is {e}\n")

# .dtype gives the data-type of the array
f = a.dtype
print(f"The data-type of the array is {f}\n")

# Obtaining the transpose of the matrix
g = a.T
print(f"Transpose of the array is:\n{g}")

Generated array is:
[[ 7  2 10]
 [10  6  1]
 [ 1 10  3]]

Shape of the array is (3, 3)

The array is 2-D

Total number of elements in the array is 9

The data-type of the array is int32

Transpose of the array is:
[[ 7 10  1]
 [ 2  6 10]
 [10  1  3]]


### Operations on array

In [15]:
import numpy as np
from numpy import dot, sum as add, mean, std, maximum, minimum, sqrt, exp, modf
from numpy.random import randint, randn

a = randint(1, 11, (3, 3))
print(f"Generated array is:\n{a}\n")

# Adding element-wise in an array
b = a + 5
print(f"Adding 5 to all elements in the generated array gives:\n{b}\n")

c = a + a
print(f"Adding generated array twice gives:\n{c}\n")

# Multiplying element-wise in an array
d = a * 3
print(f"Multipyling generated array with 3 gives:\n{d}\n")

# Dot-product of the matrices "a" & "b"
e = dot(a, b)
print(f"Dot-product of the a and b is:\n{e}\n")

# Sum of all the elements of the array "a"
f = add(a)
print(f"Sum of all the elements of array a is {f}\n")

# Mean of the array
g = mean(a)
print(f"The average of the elements of the array is {g:.2f}\n")

# Standard deviation of the array
h = std(a)
print(f"The standard deviation of the array is:\n{h:.2f}\n")

# Finding maximum of the array
i = np.max(a)
print(f"The maximum number from the array is {i}\n")

# Finding minimum of the array
j = np.min(a)
print(f"The minimum number from the array is {j}\n")

# Finding the square root of the elements of the array
k = sqrt(a)
print(f"The square root of the elements of the array is:\n{k}\n")

# Finding the maximum element-wise between two arrays
l = maximum(a, b)
print(f"The maximum element-wise between a and b is:\n{l}\n")

# Finding the minimum element-wise between two arrays
m = minimum(a, b)
print(f"The minimum element-wise between a and b is:\n{m}\n")

# Finding the exponential of the elements of the array
n = exp(a)
print(f"The exponential of the elements of the array is:\n{n}\n")

q = randn(3, 3) * 10
print(f"New generated array with random numbers is:\n{q}\n")

# Finding the fractional and integral parts of the elements of the array
[o, p] = modf(q)
print(f"The fractional part of the elements of the array are:\n{o}\n")
print(f"The integral part of the elements of the array are:\n{p}\n")

Generated array is:
[[ 4  7  1]
 [ 6  1  1]
 [ 6  9 10]]

Adding 5 to all elements in the generated array gives:
[[ 9 12  6]
 [11  6  6]
 [11 14 15]]

Adding generated array twice gives:
[[ 8 14  2]
 [12  2  2]
 [12 18 20]]

Multipyling generated array with 3 gives:
[[12 21  3]
 [18  3  3]
 [18 27 30]]

Dot-product of the a and b is:
[[124 104  81]
 [ 76  92  57]
 [263 266 240]]

Sum of all the elements of array a is 45

The average of the elements of the array is 5.00

The standard deviation of the array is:
3.27

The maximum number from the array is 10

The minimum number from the array is 1

The square root of the elements of the array is:
[[2.         2.64575131 1.        ]
 [2.44948974 1.         1.        ]
 [2.44948974 3.         3.16227766]]

The maximum element-wise between a and b is:
[[ 9 12  6]
 [11  6  6]
 [11 14 15]]

The minimum element-wise between a and b is:
[[ 4  7  1]
 [ 6  1  1]
 [ 6  9 10]]

The exponential of the elements of the array is:
[[5.45981500e+01 1.09663

### Reshaping arrays

In [16]:
from numpy.random import randint

a = randint(1, 11, (2, 8))
print(f"Generated array is:\n{a}\n")

# Reshaping the array
# .reshape() function may raise an error if the total number of elements in the array does not match the new shape
b = a.reshape(4, 4)
print(f"After reshaping, the array generated is:\n{b}\n")

# Flattening the MD arrays
c = a.flatten()
print(f"After flattening, the array is:\n{c}\n")

# 1-D view of MD array
d = a.ravel()
print(f"The 1D view of multi-dimensional array is:\n{d}")

Generated array is:
[[ 1  7  7 10  6  7  8  9]
 [ 5  9  7  3  3  8  2  3]]

After reshaping, the array generated is:
[[ 1  7  7 10]
 [ 6  7  8  9]
 [ 5  9  7  3]
 [ 3  8  2  3]]

After flattening, the array is:
[ 1  7  7 10  6  7  8  9  5  9  7  3  3  8  2  3]

The 1D view of multi-dimensional array is:
[ 1  7  7 10  6  7  8  9  5  9  7  3  3  8  2  3]


### Indexing and Slicing arrays

In [17]:
from numpy.random import randint

a = randint(1, 11, (3, 3))
print(f"Generated array is:\n{a}\n")

# Indexing
b = a[2, 1] # OR a[2][1]
print(f"Element at 3rd row and 2nd column is {b}\n")

# Slicing
c = a[:, :2]
print(f"Sliced array is:\n{c}\n")

Generated array is:
[[1 6 3]
 [6 8 4]
 [4 6 3]]

Element at 3rd row and 2nd column is 6

Sliced array is:
[[1 6]
 [6 8]
 [4 6]]



#### Boolean Indexing

- The indexing which is done on the basis of whether the condition being evaluated as`True` or `False` is called `Boolean Indexing`

- The elements which matches the condition specified in the place of indexing is shown as `True` and rest elements are shown as `False`

- Boolean Indexing results in the generation of the array consisting of only 2 values:
    - `True`
    - `False`

- The condition which is used to filter out the elements from the array is said to be the `mask`

In [18]:
from numpy.random import randint

a = randint(1, 11, (5))
print(f"Generated array is:\n{a}\n")

# Boolean Indexing
b = a > 5
print(f"Boolean Indexing result is:\n{b}\n")

# Using Boolean Indexing to filter elements
c = a[b]
# Here, the boolean array b is used as a mask to filter elements from array a
print(f"Filtered elements from array using Boolean Indexing:\n{c}\n")

Generated array is:
[7 6 2 1 1]

Boolean Indexing result is:
[ True  True False False False]

Filtered elements from array using Boolean Indexing:
[7 6]



#### Fancy Indexing

- Fancy indexing is the method, in which, it takes the arrays of the same length as the arguement inside the indexing braces (`[]`).

- Instead of looping or slicing, we can pass a list of indices directly to access elements

- If you didn't get the theory, see the example of code below:

In [19]:
from numpy.random import randint

a = randint(1, 11, (2, 3))
print(f"Generated array is:\n{a}\n")

# Fancy Indexing
b = a[[0, 1], [2, 0]]
# The above line of code is accessing the elements at point (0, 2) and (1, 0)  
print(f"Fancy Indexing result is:\n{b}\n")

Generated array is:
[[3 3 9]
 [1 6 7]]

Fancy Indexing result is:
[9 1]



#### Broadcasting

- Broadcasting allows us to perform operations on arrays of different shapes

- The array with lower dimensions is automatically expanded to match the shape of the bigger array

- If the 2 arrays don't have the same shape, then they are compared element-wise from the right, and applies the rules of the broadcasting if:
    1. Dimensions of the arrays are same
    2. Dimension of one of the array is 1

- If those above 2 conditions don't matches, it raises the error

In [20]:
from numpy.random import randint

a = randint(1, 11, (3,))
print(f"Generated array 1 is:\n{a}\n")

b = randint(1, 11, (2, 1))
print(f"Generated array 2 is:\n{b}\n")

# Broadcasting
c = a + b
print(f"Broadcasting result is:\n{c}\n")

Generated array 1 is:
[ 3 10  2]

Generated array 2 is:
[[2]
 [8]]

Broadcasting result is:
[[ 5 12  4]
 [11 18 10]]



### Copy and View method

|**Copy**|**View**|
|---------|---------|
|The `.copy()` method creates another copy of the original array.|The `.view()` method creates the copy of the original array such that the both arrays are depended on each other|
|The changes done in 1st array won't be reflected in the 2nd array and vice-versa|That means, the change in 1st array would be reflected in the 2nd array and vice-versa|
|In other words, the array generated from the method does have pass by value|In other words, the array generated from the method have pass by reference |

In [21]:
from numpy import array

a = array([[1, 2], [3, 4]])
print(f"Matrix A:\n{a}\n")

# .copy() method
b = a.copy()
print(f"Matrix B:\n{b}\n")
b = b + 5
print(f"After modification of B:\nMatrix A:\n{a}\nMatrix B:\n{b}\n")

# .view() method
c = a.view()
print(f"Matrix C:\n{c}\n")
c[1][1] = 5
print(f"After modification of C:\nMatrix A:\n{a}\nMatrix C:\n{c}\n")

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[1 2]
 [3 4]]

After modification of B:
Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[6 7]
 [8 9]]

Matrix C:
[[1 2]
 [3 4]]

After modification of C:
Matrix A:
[[1 2]
 [3 5]]
Matrix C:
[[1 2]
 [3 5]]



## Note

- This notebook yet does not covers the whole NumPy package of Python

- So, it is recommended to visit the offical documentation of the NumPy if you want to know about it in more depth or look for the topics not covered in the notebook 